version: '3'
services:

  bot:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: "/bin/sh"
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    volumes:
        - .:/app
    environment:
        RACK_ENV: "development"
        WEBAPI_API_KEY: "af5876e4-2b63-4f98-a903-807187ffe2d2"
